<div id="" class="row">
    <div id="" style="margin-bottom: 1em;"  class="col-xl-12 text-center col-lg-12 col-md-12 col-sm-12 col-12">
        <a class="" style="text-decoration:none; border: 1px solid black; border-radius:0.25em; padding:0.25em 0.5em; background-color:#EFEFEF;" href="index.php?ctl=motrarplantabus">Inscribir Pasajeros</a>
    </div>

    <div id="desplegar_tabla_Info_bus" class="col-xl-12 text-center col-lg-12 col-md-12 col-sm-12 col-12">
        <input id="" type="button" value="Desplegar Información Bus">
    </div>
</div>