
<div id="" class="col-xl-12 text-center col-lg-4 col-md-4 col-sm-4 col-4">
<input class="btn btn-success" type="submit" name="generapdfocupacionbus"  value="html2pdf" onclick="insertaIdDestino(<?php echo($codDes);?>); seleccionaPlaza(<?php echo($plaza);?>)">
</div>

<div id="" class="col-xl-12 text-center col-lg-4 col-md-4 col-sm-4 col-4">
<input class="btn btn-success" onclick="descargarPDF('reporte2','Archivo')" type="submit" name="" value="jquery">
</div>

<?php /*
<!-- <li><a href="index.php?ctl=destinoscondescuentos"><i style="color:red;" class="fa-solid fa-percent"></i><span> Escribe tu sugerencia</span></a></li>-->                                                                        
*/ ?>