<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> Su Agencia</a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="index.php?ctl=infoagenciaviajes">Perfil</a> 
            <a class="dropdown-item" href="index.php?ctl=modificacioninfoagenciaviajeslogeada">Modificar Perfil</a> 
            <a class="dropdown-item" href="index.php?ctl=cambiousernamecontrasenaagenciaviajes">Username/Password</a> 
            <a class="dropdown-item" href="index.php?ctl=eliminarAgenciaviajesLogeada">Darse de baja</a> 
            
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Personal Agencia Viajes (ampliable V2)</a>

        <!--  <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Otros (ampliable V2)</a>-->
        </div>
</li>