<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user"></i> Donde Comer!</a>
            
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="index.php?ctl=comerennoja"><i class="fas fa-umbrella-beach"></i> Noja</a>
            <a class="dropdown-item" href="index.php?ctl=perfilcliente"><i class="fas fa-eye"></i> Santoña</a>
        </div>   
    </li>
</nav>