
      
      
      <div class="row">
        <div class="col-xl-12 text-center col-lg-12 col-md-12 col-sm-12 col-12">
          <nav class="navbar navbar-expand-lg navbar-light"><!--bg-light-->

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNavDropdown" style="text-align: center;">

              <div id="navegacion_filtros" class="cuadros_navegacion">

              <?php include $_SERVER['DOCUMENT_ROOT'] . '\Verano-2023/app\plantillas\bloques\navegacion\navegacionDrcha\restaurantes.inc'; ?>
               
              </div>

            </div>
          </nav>
        </div>
      </div>

      


      
      
      


      
