
<li><a class="nav-link" href="index.php?ctl=logearCliente"><i class="fas fa-users"></i> Login Clientes</a></li>
<li><a class="nav-link" href="index.php?ctl=logearpropietarios"><i class="fas fa-users"></i> Login Propietarios</a></li>

<li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" 
          role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-users"></i> Logins</a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="index.php?ctl=logearCliente"><i class="fas fa-users"></i> Clientes</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="index.php?ctl=logearagenciaviajes"><i class="fas fa-store-alt"></i> Agencias de Viajes</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="index.php?ctl=logearagenciabuses"><i class="fas fa-store-alt"></i>Agencias de Buses</a>

              <!--  <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Otros</a>
              
</li>-->