<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" 
    role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-store"></i> Propietarios</a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="index.php?ctl=infoagenciabuses"><i class="fas fa-eye"></i> Perfil</a> 
            <a class="dropdown-item" href="index.php?ctl=modificacioninfoagenciabuseslogeada"><i class="fas fa-edit"></i> Modificar Perfil</a> 
            <a class="dropdown-item" href="index.php?ctl=eliminaragenciabuseslogeada"><i class="fas fa-trash-alt"></i> Darse de baja</a> 
            
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="index.php?ctl=crear_menu"><i class="fas fa-utensils"></i> ¡Crear Menú!</a>
            <a class="dropdown-item" href="index.php?ctl=seleccionar_menu"><i class="fas fa-utensils"></i> ¡Seleccionar Menú!</a>
            <a class="dropdown-item" href="index.php?ctl=eliminar_menu"><i class="fas fa-utensils"></i> ¡Eliminar Menú!</a>

            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="index.php?ctl=creardescuento"><i class="fas fa-utensils"></i> ¡Crear Descuento!</a>
            
            
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Personal Agencia Buses (ampliable V-2)</a>

      <!--  <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Otros</a>-->
        </div>
</li>