<?php

const LOCALIDADES="'Alberite','Santoña','Zarautz','Fuenterrabía','San Sebastián',
'Noja','Biarritz','Laredo','Santander','Castro Urdiales','Hendaya','Saint-Jean-de-Luz','Getaria','Zumaia',
'Orio','Somo','Plentzia','Lekeitio','Isla','Ajo','Bakio','Ondarroa','Deba','Somorrostro'";


const CONEXIONBASEDEDATOS = "/Verano-2022/app/conf/configuracionfantasma.inc"; 

const CONEXIONBASEDEDATOSMYSQLI = '/Verano-2022/app/conf/configuracionmysqli.inc'; // MYSQLI

const LOCALIDADREPOSITORIO= "/Verano-2022/app/plantillas/bloques/sessiones/LocalidadRepositorio.inc";  

const CLIENTEREPOSITORIO = "/Verano-2022/fuente/Repositorio/ClienteRepositorio.inc";
const PROPIETARIOREPOSITORIO = "/Verano-2022/fuente/Repositorio/PropietarioRepositorio.inc";
const AGENCIAVIAJESREPOSITORIO = "/Verano-2022/fuente/Repositorio/AgenciaViajesRepositorio.inc";
const AGENCIABUSESREPOSITORIO = "/Verano-2022/fuente/Repositorio/AgenciaBusesRepositorio.inc";

const MENUREPOSITORIO = "/Verano-2022/fuente/Repositorio/MenuRepositorio.inc";
const MENUBASICOREPOSITORIO = "/Verano-2022/fuente/Repositorio/MenuBasicoRepositorio.inc";
const MENUMODREPOSITORIO = "/Verano-2022/fuente/Repositorio/MenuMODRepositorio.inc";
const MENUPERSONALREPOSITORIO = "/Verano-2022/fuente/Repositorio/MenuPersonalRepositorio.inc";


const PERSONAREPOSITORIO = "/Verano-2022/fuente/Repositorio/PersonaRepositorio.inc";
const PASAJEROREPOSITORIO = "/Verano-2022/fuente/Repositorio/PasajeroRepositorio.inc";

const BUSREPOSITORIO = "/Verano-2022/fuente/Repositorio/BusRepositorio.inc";
const DESTINOREPOSITORIO = "/Verano-2022/fuente/Repositorio/DestinoRepositorio.inc";

const VIAJARREPOSITORIO = "/Verano-2022/fuente/Repositorio/ViajarRepositorio.inc";

const SESIONS= "/Verano-2022/app/plantillas/bloques/sessiones/session.inc";  

?>