<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user"></i> Clientes</a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="index.php?ctl=tusdestinoscontratados"><i class="fas fa-umbrella-beach"></i> Tus destinos contratados</a> 
          <a class="dropdown-item" href="index.php?ctl=perfilcliente"><i class="fas fa-eye"></i> Perfil</a>
          <a class="dropdown-item" href="index.php?ctl=modificacliente"><i class="fas fa-edit"></i> Modificar Perfil</a> 
          <a class="dropdown-item" href="index.php?ctl=autobajacliente"><i class="fas fa-trash-alt"></i> Baja Cliente</a> 
      </div>   
</li>