  <?php /*
<div id="register_password">
  
    <div class="row" >
        <div id="register" class="col-xl-12 text-center col-lg-4 col-md-12 col-sm-12 col-12">
            <a class="" href="index.php?ctl=nuevacuentacliente"><i class="fas fa-sign-in-alt"></i> Register</a> <br>
        </div>
    </div>
   

    <div class="row">
        <div id="password" class="col-xl-12 text-center col-lg-4 col-md-12 col-sm-12 col-12">
            <a href="index.php?ctl=forgotyourpassword"> Forgot your Password ?</a> 
        </div>
        
    </div>
</div> 
*/ ?>