

<div class="container">
  <div id="directos" class="row">
    <div class="col-xl-6 text-center col-lg-6 col-md-6 col-sm-12 col-12">
      <a href="index.php?ctl=cuadrobuscadoresnegocios"><i class="fas fa-utensils"></i> Bares y Restaurantes!</a>
    </div>

    <div class="col-xl-6 text-center col-lg-6 col-md-6 col-sm-12 col-12">
      <a href="index.php?ctl=mostrartodosdestinos"><i class="fas fa-umbrella-beach"></i> Agenda del Verano 2022</a>
    </div>
  </div>
</div>