
<?php  require_once $_SERVER['DOCUMENT_ROOT'] . '/Verano-2022/app/plantillas/bloques/menus/formMenu-7.inc';?>

               
<style>
    .foto_fondomenu{width: 100px; height: 130px; margin: 0.5em;}
   /* #menu_MOD-7{display: none;} */
</style>



<style>
    
#caja{border:1px solid #006293; border-radius: 5px;  margin: auto; padding:1em;
background-color: #f6f6f6; margin-bottom: 1em; margin-top: 1em;
box-shadow: inset 0px 0px 20px 4px #c1c1c1;}

#buscadordestinos input, #buscadordestinos select {
    border: 1px solid #006293; width: 51%;
    border-radius: 5px;     padding: 0.2em;
    margin: 0.2em 0.2em 0em 0em; color: #006293;
}

#consultar input{ border-radius: 1em; margin-top: 1em;}

.col-xl-12, .col-lg-12, .col-md-12, .col-sm-12, .col-12 { flex: 0 0 auto; width: 100%; text-align: center;}
h2{padding: 0em; text-align: left; text-decoration: underline; }
.contenedor_partemenu{border:1px solid black; padding:0.5em}

</style>