<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" 
    role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-store"></i> Su Agencia de Buses</a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="index.php?ctl=infoagenciabuses"><i class="fas fa-eye"></i> Perfil</a> 
            <a class="dropdown-item" href="index.php?ctl=modificacioninfoagenciabuseslogeada"><i class="fas fa-edit"></i> Modificar Perfil</a> 
            <a class="dropdown-item" href="index.php?ctl=eliminaragenciabuseslogeada"><i class="fas fa-trash-alt"></i> Darse de baja</a> 
            <a class="dropdown-item" href="index.php?ctl=mostrartodosdestinosquevaunaagenciabuseslogeada"><i class="fas fa-umbrella-beach"></i> Destinos a cubrir</a> 
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Personal Agencia Buses (ampliable V-2)</a>

      <!--  <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Otros</a>-->
        </div>
</li>


<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-bus-alt"></i> Area de Buses</a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="index.php?ctl=nuevobus"><i class="fas fa-bus"></i> Nuevo Bus</a> 
                <!-- <a class="dropdown-item" href="index.php?ctl=nuevobus">Eliminar Bus (Hecho)</a>-->
                <!-- <a class="dropdown-item" href="index.php?ctl=modificarbus">Modificar un Bus (Hecho)</a>-->
                  <a class="dropdown-item" href="index.php?ctl=todosbusesdeunaagenciabuses"><i class="fas fa-eye"></i> Todos los Buses</a> 
        </div>
</li>