 <div class="table-responsive"> 
    <table class="table table-bordered table-hover">
        <thead class="table-active">
            <th><div id="" style="margin-top: 0.5em;" class="row"> 
                <div class="col-xl-12 text-center col-lg-12 col-md-12 col-sm-12 col-12">
                    <input type="submit" onclick="eliminarVariasReservasssssss()" name="eliminarvariasreservas" value="Eliminar Varias Reservas">    
                </div> 
            </th>

            <th style="width: 50%;">
                <div class="row">
                    <div id="" class="col-xl-12 text-center">
                        <label for="estaseguroa">
                        <input id="estaseguroa" type="checkbox" name="asegura"> Estoy seguro de hacer los cambios.</label>
                    </div>
                </div>

                <div id="botones">
                    <input type="submit" name="guardarcambiosbilletes" value="Guardar Cambios">
                    <input type="reset" value="Valores Iniciales">
                </div>
            </th>
        </thead>
    </table>
    <?php include $_SERVER['DOCUMENT_ROOT'] . '/Verano-2022\app\plantillas\bloques\destinos\info_Recaudado.inc'; ?>

    
</div>


