  <?php  //include $_SERVER['DOCUMENT_ROOT']   . TEMPORADA . '/app/plantillas/bloques/destinos/infoTablaBusDestino/--modificarEstadosReservas.inc'; ?>
    <div class="table-responsive"> 
        <table class="table table-bordered table-hover">
            <thead class="table-active">
                <th><div id="" style="margin-top: 0.5em;" class="row"> 
                    <div class="col-xl-12 text-center col-lg-12 col-md-12 col-sm-12 col-12">
                        <input type="submit" onclick="eliminarVariasReservasssssss()" name="eliminarvariasreservas" value="Eliminar Reservas">    
                    </div> 
                </th>

                <th style="width: 50%;">
                    <div class="row">
                        <div id="" class="col-xl-12 text-center">
                            <label style="font-size: 0.7em;" for="estaseguroa">
                            <input  id="estaseguroa" type="checkbox" name="asegura"> Estoy seguro de hacer los cambios.</label>
                        </div>
                    </div>

                    <div id="botones" class="row" style="margin-bottom: 0.5em;">

                        <div class="col-xl-12 text-center col-lg-12 col-md-12 col-sm-12 col-6">
                            <input type="submit" name="guardarcambiosbilletes" value="Guardar">
                        </div>

                        <div class="col-xl-12 text-center col-lg-12 col-md-12 col-sm-12 col-6">
                            <input type="reset" value="Limpiar">
                        </div>

                    </div>

                </th>
            </thead>
        </table>
    </div>