 
 <!-- En el area del HEAD -->
<link href='http://fonts.googleapis.com/css?family=Snowburst+One' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Roboto Condensed' rel='stylesheet'>
<div style="font-family:'Snowburst One';">Esta fuente llamada Snowburst se carga desde Google Font</div>

 
 <div class="container">
    <div class="row" >
        <div class="col-xl-4 col-lg-4 col-md-4 col-sm-4 col-4">
            <input id="button_logeo_cliente" type="button" onclick="aparece()" value="Clientes Predeterminados">
        </div>

        <div class="col-xl-4 col-lg-4 col-md-4 col-sm-4 col-4">
            <input id="button_logeo_agenciasviajes" type="button" onclick="aparece()" value="Agencias de Viajes Predeterminadas">
        </div>

        <div class="col-xl-4 col-lg-4 col-md-4 col-sm-4 col-4">
            <input id="button_logeo_agenciasbuses" type="button" onclick="aparece()" value="Agencias de Buses Predeterminadas">
        </div>

    </div>
</div>


<div class="row">
    <div id="logeo_cliente" class="col-xl-4 col-lg-4 col-md-12 col-sm-12 col-12"><br>

        <h6>Logueo Cliente roll=> cliente</h6>
            <p>
                Adrián Laya   adri82/alberite <spam style="color:red;">admin</spam> <br>
                Javier Hernan javi82/alberite <br>
                Eduardo       edu82/alberite  <br>
                Dayanna       dayanna82/alberite <br>
                Borja         borja82/alberite <br>
            </p>
    </div> 

    <div id="logeo_agenciaviajes" class="col-xl-4 col-lg-4 col-md-12 col-sm-12 col-12"><br>

        <h6>Logueo Agencia de Viajes roll=> agenciaviajes</h6>
            <p>
                Gran Reserva     reser21/reser21 <br>
                GO TRAVELL       gotravell21/gotravell21 <br>
                ROTUPRINT        rotu21/rotu21 <br>
                AZUL MARINO      azulmarino21/azulmarino21 <br>
                Zafiro Tours     zafiro21/zafiro21 <br>
                ---Pruebas--- <br>
                ViajesLaya           viajeslaya21/viajeslaya21
            </p>
    </div>

    <div id="logeo_agenciabuses" class="col-xl-4 col-lg-4 col-md-12 col-sm-12 col-12"><br>

        <h6>Logueo Agencias de Buses roll=> agenciabuses</h6>
            <p>
                Yanguas ---            yanguas21/yanguas21 <br>
                Riojacar ---           riojacar21/riojacar21 <br>
                Victor Bayo ---        victorbayo21/victorbayo21 <br>
                Jimenez  ---           jimenez21/jimenez21 <br>
                Logrobus ---           logrobus21/logrobus21 <br>
                ---Pruebas--- <br>
                Autocares Laya ---     autocareslaya21/autocareslaya21  "nueva"
            </p>
    </div>
</div>
