
<style>
#navegacion_filtros{
  display: block;
  margin: auto;
  padding: 1em;

}

 #navegacion_filtros #filtro_destinos{display: block;}

  #navegacion_filtros #filtro_destinos li{
  border-radius: 0.1em; border:1px solid black; text-align:left;
  background-color: #FFFFFF; padding: 0em 0.5em; margin: 0.25em 0em;
}

#navegacion_filtros #filtro_destinos li:hover{
   font-weight: bold;
   background-color: #DEB584;
}



  .cuadros_navegacion{border: 1px solid #00629A; border-radius: 0.5em; box-shadow: inset 0px 0px 20px 4px #c1c1c1;}
  .cuadros_navegacion:hover{ box-shadow: 1px 1px 10px 1px #00629A; border-radius: 0.5em;}


</style>