


<style>
#inscribir_pasajeros{margin: 0.5em;}

#bus_vacio{margin: 0.5em;}
#bus_vacio h6{
    color: red;
}

@media only screen and (min-width: 360px) and (max-width: 430px){
th, td {
    font-size: 0.6em;
   
/*
vertical-align: baseline;
vertical-align: text-top;
vertical-align: text-bottom;
vertical-align: sub;
vertical-align: super;
*/
}




.table>:not(caption)>*>* {
    padding: 0rem 0rem;
    background-color: var(--bs-table-bg);
    background-image: linear-gradient(var(--bs-table-accent-bg),var(--bs-table-accent-bg));
    border-bottom-width: 1px;
}

}

th, td {
    
    vertical-align: middle;

}

</style>