<style>
#container_notepierdas h5{border: none; text-decoration: underline; text-align:center;}
.tarjeta_foto img{vertical-align: middle; width: 150px;}

@media only screen and ( min-width: 1200px) and (max-width: 3000px) {
 .container__notepierdas {max-width: 700px;margin: auto;}
}

@media only screen and ( min-width: 950px) and (max-width: 1199px) {
 .container__notepierdas {max-width: 700px; margin: auto;}
}

@media only screen and ( min-width: 576px) and (max-width: 780px) {
 .container, .container-sm {max-width: 700px;}
}
@media only screen and ( min-width: 602px) and (max-width: 1000px) {
.container, .container-fluid, .container-lg, .container-md, .container-sm, .container-xl, .container-xxl {
/*padding-right: 1.2em!important; padding-left: 1.2em!important;*/
}
}

@media only screen and ( min-width: 421px) and (max-width: 600px) {
.container, .container-fluid, .container-lg, .container-md, .container-sm, .container-xl, .container-xxl {
width: 100%; padding-right: 0.5em!important; padding-left: 0.5em!important;
}
}

@media only screen and ( min-width: 200px) and (max-width: 420px) {
.container, .container-fluid, .container-lg, .container-md, .container-sm, .container-xl, .container-xxl {
width: 100%; padding-right: 0.03em!important; padding-left: 0.03em!important;
}

.row {
--bs-gutter-x: 0.2rem;
}




/*
<!--https://www.w3bai.com/es/css/css3_buttons.html   Meter esto cuando se pueda


<button class="button">Click Me</button>
-->


<style>
.button {
  display: inline-block;
  padding: 15px 25px;
  font-size: 24px;
  cursor: pointer;
  text-align: center;	
  text-decoration: none;
  outline: none;
  color: #fff;
  background-color: #4CAF50;
  border: none;
  border-radius: 15px;
  box-shadow: 0 9px #999;
}

.button:hover {background-color: #3e8e41}

.button:active {
  background-color: #3e8e41;
  box-shadow: 0 5px #666;
  transform: translateY(4px);
}
</style>




<style>
.container, .container-lg, .container-md, .container-sm {/*max-width: 1200px;*/}

.partes{margin: 0.5em;}
p{/*font-size: 0.8em; text-align: left;*/}
h5 {/*color: #006293; border-bottom: none; text-align: end;*/}
/*
@media only screen and ( min-width: 621px) and (max-width: 2000px) {
.tarjeta_barrestaurante h5 {
    color: #006293;
    border-bottom: none;
    /* text-align: end;
    font-size: 0.9em;
    margin-left: 7.2em;
    text-decoration: underline;
} 
}
@media (min-width: 492px){}
@media only screen and ( min-width: 200px) and (max-width: 620px) {}  
*/
</style>





















<style>
    label{text-align: left;}
#caja{
    text-align: left;
    border:1px solid #006293; border-radius: 5px;  margin: auto; padding:1em;
    background-color: #f6f6f6; 
    box-shadow: inset 0px 0px 20px 4px #c1c1c1;}


#filtros select, #dondecomer select{width: 160px;}

</style>


