 
<style>
#navegacion_restaurantes li{margin: 0.2em 0em;
text-align: center;
background-color: #EFEFEF;
padding: 0.25em;}

#navegacion_restaurantes li:hover{
background-color: #88DCBD;
}

#navegacion_restaurantes li a{font-weight: bold;}

summary{
text-align: left;
}

summary:hover{
font-weight: bold;
background-color: #88DCBD;
}

#navegacion_restaurantes li{    border: 1px solid black;
    border-radius: 3px;}
 #navegacion_restaurantes li h6{
    margin: 0em;
 }

</style>