
<style>
    h4{margin: 0.5em;}
    .agencia{margin-top: 0em;}
    .fecha{color:green; margin-top: 0px!important}
</style>

<style>
.previous, .next{color:white; background-color:#006293;}
.button_aparecernegocios{padding: 0.3em; text-align:center; background-color: yellow; margin: 0.5em;}
.deseleciona{font-size: 0.8em; border: 1px solid #006293; border-radius:1em; padding-left:1em; color:#006293;
                        padding-right:1em; width: 120px;}

    .botones_mostrarFotosLocalidad input{height: 16px; margin: 0.5em; border-radius: 1em;}
/*#ab{ background-image: url("web/imagenes/localidades/imgLaredo1.jpg");}*/
.fa-solid{
    margin: 0.25em;
}

</style>



<style>
/* Para ambos archivos */

h5, i{text-align: center; color: #006293; border-bottom: none; margin: 0em;}
h5{border-bottom: 1px solid #006293; margin-top: 1em; padding-bottom: 0.1em;}
h6{text-decoration: underline; margin-bottom: 0em; text-align: left; padding-left: 0.5em;}
p{font-size: 1em; margin-top: -0.5em; margin-bottom: 0.3em;}

.tarjeta_barrestaurante_localidad{margin-top: 0.5em; padding:0em;}


#nohay{color:red; font: 1em sans-serif; text-align: center; margin-top: 1em;}

.fa-solid, .fas {
    /*font-family: "Font Awesome 6 Free";
    font-weight: 400; font-size: 0.9em; */
}





article{border: 1px solid #006293; border-radius: 3px; padding: 0.2em;
    box-shadow: inset 0px 0px 20px 4px #c1c1c1;
}

.articuloconboton h6 span{ color: #212721;}

.tarjeta_ancha .destino{margin-top: 0.5em;}
.tar .w-100{border-radius: 0.2em;}
#redes_sociales a{margin-right: 0.5em;}

/* Cards */
.comunidad,.destino,.fecha,.info_plazas,.precio,.agencia {text-align: center;}
.articulo, .publicidad{
  background-color: #F8F9FA; border-radius: 0.4em; border: 2px solid #c1c1c1; padding: 0.1em 0.3em 0.3em; 
  /*box-shadow: 5px 5px 5px #888888;*/ 
  box-shadow: inset 0px 0px 20px 4px #c1c1c1;}

  .articulo:hover{ box-shadow: 1px 1px 10px 1px #888888; border-radius:  0.2em;}


.descripcion{padding: 1em;}
.descrip_negocio{margin-top: 0.5em;}

.comunidad{color: #006293; font-weight: bold; margin-bottom: 0.5em; font-size: 0.8em;}
.destino{color: #212721; text-decoration: underline; font-weight: bold; margin-top: 0em; margin-bottom: 0em;}

.destino a {/*font-size: 0.5em;*/ text-decoration: underline; }
.destino p{padding: 0em;}

.info_plazas{font-size: 0.7em; margin-top: -1.4em;}
.precio{margin-top: -1em; margin-bottom: -0.1em; } 
.textoprecio{font-size: 1.3em; float: right; text-align: right; }
.apuntar, .apuntar2{ border-radius:0.3em;}
.apuntar{ border: 1px solid #006293;}
.apuntar2{ color: red; border: 1px solid red;}
#boton_apuntar{ padding-top: -2em; border-radius: 0.5em; margin: auto;}

@media only screen and (min-width: 1400px) and (max-width: 3000px) {
.precio{font-size: 1.5em; margin-top: -0.6em; margin-bottom: 0.05em;}
}

@media only screen and (min-width: 970px) and (max-width: 1400px) {
.comunidad{ font-size: 0.8em; margin: auto;}
.destino a {/*font-size: 0.49em;*/ text-decoration: underline;}
.fecha{ font-size: 0.6em;}
.info_plazas{font-size: 0.7em; text-align: center; margin-top: -1.4em;} 
}

@media only screen and (min-width: 970px) and (max-width: 1400px) {
.comunidad{ font-size: 0.8em; margin: auto;}
.destino a {/*font-size: 0.45em;*/ text-decoration: underline;}
.fecha{ font-size: 0.6em;}
.info_plazas{font-size: 0.7em; text-align: center; margin-top: -1.4em;} 

.container{max-width: 2000px;}
}

@media only screen and (min-width: 740px) and (max-width: 999px) {

header img{padding: 0px; height: 550px; }
.fecha, .agencia{font-size: 0.55em;}
.a{width: 375px; height:140px; margin-top: 7.5em;}
.plaza{font-size: 1em;} 
h2{font-size: 1.3em;}
header img{height:200px;}
.fotoplantabus{margin-top: 6em; }

.fotodestino{height: 120px;}

.info_plazas {font-size: 0.6em;}
}
/*--------------------------------*/

@media only screen and (min-width: 600px) and (max-width: 790px) {
    .fotodestino{border-radius: 0.3em; z-index: -1; width: 100%; height: 120px; }
}
 </style>


<style>

@media only screen and (max-width: 420px){
    .modal-content{ max-width: 380px; margin:auto;}
}

@media only screen and (min-width: 421px) and (max-width: 4000px) {
.modal-content{max-width: 700px; margin:auto;}
}
</style>