
<input type="submit" name="modificardestino" value="Modificar" onclick="deselecionaTodosChecksDestinos(),selecciona('<?php echo($ref_Destino);?>')">                    

<?php /*
<input class="boton_suspenderviajeeee" type="submit" name="ocupacionbus" value="Ocupación del Bus" onclick="deselecionaTodosChecksDestinos(),selecciona('<?php echo($ref_Destino);?>')">                
*/ ?>

<style>
    input{margin: 0.5em;}
</style>

    







 