<div id="carrusel" class="container-fluid" >
    <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
        
            <div class="carousel-item active">
            <img  class="d-block w-100" src="web/imagenes/carrusel/<?php echo $foto_destinosLocalidad[0]; ?>" alt="Noja">
            <h6><?php echo $destinosLocalidad[0]; ?></h6>
            </div>

            <div class="carousel-item">
                <img class="d-block w-100" src="web/imagenes/carrusel/<?php echo $foto_destinosLocalidad[0]; ?>" alt="Casto Urdiales">
                <h6><?php echo $destinosLocalidad[1]; ?></h6>
            </div>

            <div class="carousel-item">
            <img class="d-block w-100" src="web/imagenes/carrusel/<?php echo $foto_destinosLocalidad[0]; ?>" alt="Zarautz">
            <h6><?php echo $destinosLocalidad[2]; ?></h6>
            </div>
        
            <div class="carousel-item">
            <img class="d-block w-100" src="web/imagenes/carrusel/<?php echo $foto_destinosLocalidad[0]; ?>" alt="San Juán de Luz">
            <h6><?php echo $destinosLocalidad[3]; ?></h6>
            </div>

            <div class="carousel-item">
            <img class="d-block w-100" src="web/imagenes/carrusel/<?php echo $foto_destinosLocalidad[0]; ?>" alt="Laredo">
            <h6><?php echo $destinosLocalidad[4]; ?></h6>
            </div>
            
        </div>
    </div>
</div>