<!--Tarjeta vacia-->
    


    <div class="row negociosolo" style="margin-top: 1em;">
        <div class='col-xl-12 text-center col-lg-12 col-md-12 col-sm-12 col-12'>
            <h6 class="espaciovacio">
                Espacio Reservado para su anuncio
            </h6>
        </div>
    </div>



<style>
  
.negociosolo{
    background-color: #F8F9FA;
    border-radius:  0.3em 0.3em 0.3em 0.3em;
    border: 1px solid #c1c1c1; 
    padding: 0.45em;
    /* box-shadow: 5px 5px 5px #888888; */
    box-shadow: inset 0px 0px 20px 4px #c1c1c1;
    
}

.negocio:hover{
     box-shadow: 1px 1px 10px 1px #888888; 
     border-radius:  0.6em;
}

.espaciovacio{
    text-align:center; margin-bottom: 10.3em;
}

</style>       



