<div class="container" >
<div class="row">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                                
    <div id="container_footer" >
    
                <div class="row"> 
                <div class="col-xl-12 text-center col-lg-12 col-md-12 col-sm-12 col-12">
                    <h4>Tourist offices</h4>
                </div>
                </div>

                <div class="row">
                    <div class="col-xl-12 text-center col-lg-12 col-md-12 col-sm-12 col-12">
                        <hr class="letra">
                    </div>
                </div>

                <div class="comunidades_destinos" class="row"> 
                        <div class="col-xl-3 text-center col-lg-3 col-md-3 col-sm-6 col-12">
                            <h5>Cantabria</h5>
                        </div>

                        <div class="row">

                           <div class="col-xl-12 text-center col-lg-12 col-md-12 col-sm-12 col-12">
                                <div class="row">
                                    <div class="col-xl-4 text-center col-lg-4 col-md-4 col-sm-4 col-4">
                                        <h6><a href="#">Santander</a></h6>
                                    </div>
                                    <div class="col-xl-4 text-center col-lg-4 col-md-4 col-sm-4 col-4">
                                        <h6><a href="https://www.cylex.es/somo/oficina-de-turismo-de-somo-11456114.html">Somo</a></h6>
                                    </div>
                                    <div class="col-xl-4 text-center col-lg-4 col-md-4 col-sm-4 col-4">
                                        <h6><a href="https://www.islacantabria.com/inicio">Isla</a></h6>
                                    </div>
                                </div>
                           </div>


                           
                           <div class="col-xl-12 text-center col-lg-12 col-md-12 col-sm-12 col-12">
                                <div class="row">
                                    <div class="col-xl-4 text-center col-lg-4 col-md-4 col-sm-4 col-4">
                                        <h6><a href="http://nojaturismo.com/">Noja</a></h6>  
                                    </div>
                                    <div class="col-xl-4 text-center col-lg-4 col-md-4 col-sm-4 col-4">
                                        <h6><a href="https://www.laredo.es/09/oficina_turismo.php">Laredo</a></h6>
                                    </div>
                                    <div class="col-xl-4 text-center col-lg-4 col-md-4 col-sm-4 col-4">
                                    <h6><a href="http://turismo.castro-urdiales.net/turcastro/planifica-tu-viaje/oficina-de-turismo">Castro-Urdiales</a></h6> 
                                    </div>
                                </div>
                           </div>

                        </div>
            
                </div>

                    <div class="col-xl-12 text-center col-lg-12 col-md-12 col-sm-12 col-12">
                        <hr class="letra">
                    </div>

                <div class="comunidades_destinos" class="row"> 
                        <div class="col-xl-3 text-center col-lg-3 col-md-3 col-sm-6 col-12">
                            <h5>Vizcaya</h5>
                        </div>

                        <div class="row">

                           <div class="col-xl-12 text-center col-lg-12 col-md-12 col-sm-12 col-12">
                                <div class="row">
                                    <div class="col-xl-4 text-center col-lg-4 col-md-4 col-sm-4 col-4">
                                        <h6><a href="https://turismo.euskadi.eus/es/oficinas-turismo/oficina-de-turismo-de-san-sebastian/aa30-12375/es/">San Sebastián</a></h6>
                                    </div>
                                    <div class="col-xl-4 text-center col-lg-4 col-md-4 col-sm-4 col-4">
                                        <h6><a href="https://hondarribiaturismo.com/">Fuenterrabía</a></h6>
                                    </div>
                                    <div class="col-xl-4 text-center col-lg-4 col-md-4 col-sm-4 col-4">
                                        <h6><a href="https://lekeitioturismo.eus/es/">Lekeitio</a></h6>
                                    </div>
                                </div>
                           </div>


                           
                           <div class="col-xl-12 text-center col-lg-12 col-md-12 col-sm-12 col-12">
                                <div class="row">
                                    <div class="col-xl-4 text-center col-lg-4 col-md-4 col-sm-4 col-4">
                                        <h6><a href="https://visitplentzia.com/">Plentzia</a></h6>  
                                    </div>
                                    <div class="col-xl-4 text-center col-lg-4 col-md-4 col-sm-4 col-4">
                                     <h6><a href="http://lekeitioturismo.eus/">Lekeitio</a></h6>
                                    </div>
                                    
                                </div>
                           </div>

                        </div>
            
                </div>

                    <div class="col-xl-12 text-center col-lg-12 col-md-12 col-sm-12 col-12">
                        <hr class="letra">
                    </div>

                <div class="comunidades_destinos" class="row"> 
                        <div class="col-xl-3 text-center col-lg-3 col-md-3 col-sm-6 col-12">
                            <h5>Guipúzcoa</h5>
                        </div>

                        <div class="row">

                           <div class="col-xl-12 text-center col-lg-12 col-md-12 col-sm-12 col-12">
                                <div class="row">
                                    <div class="col-xl-4 text-center col-lg-4 col-md-4 col-sm-4 col-4">
                                        <h6><a href="https://zumaia.eus/es/turismo/zumaia-turismo/oficina-de-turismo">Zumaia</a></h6></div>
                                    <div class="col-xl-4 text-center col-lg-4 col-md-4 col-sm-4 col-4">
                                        <h6><a href="https://www.getariaturismo.eus/es">Getaria</a></h6>
                                    </div>
                                    <div class="col-xl-4 text-center col-lg-4 col-md-4 col-sm-4 col-4">
                                        <h6><a href="https://www.turismozarautz.eus/es/">Zarautz</a></h6>
                                    </div>
                                </div>
                           </div>


                           
                           <div class="col-xl-12 text-center col-lg-12 col-md-12 col-sm-12 col-12">
                                <div class="row">
                                    <div class="col-xl-4 text-center col-lg-4 col-md-4 col-sm-4 col-4">
                                        <h6><a href="http://turismo.orio.eus/es/">Orio</a></h6>  
                                    </div>
                                </div>
                           </div>

                        </div>
            
                </div>
                       
                    <div class="col-xl-12 text-center col-lg-12 col-md-12 col-sm-12 col-12">
                        <hr class="letra">
                    </div>
                        
                <div class="comunidades_destinos" class="row"> 
                        <div class="col-xl-3 text-center col-lg-3 col-md-3 col-sm-6 col-12">
                            <h5>Francia</h5>
                        </div>

                        <div class="row">

                           <div class="col-xl-12 text-center col-lg-12 col-md-12 col-sm-12 col-12">
                                <div class="row">
                                    <div class="col-xl-4 text-center col-lg-4 col-md-4 col-sm-4 col-4">
                                        <h6><a href="https://www.hendaye-tourisme.fr/es/">Hendaya</a></h6>
                                    </div>
                                    <div class="col-xl-4 text-center col-lg-4 col-md-4 col-sm-4 col-4">
                                        <h6><a href="https://www.saint-jean-de-luz.com/homepage-es/">San Juan de Luz</a></h6>
                                    </div>
                                    <div class="col-xl-4 text-center col-lg-4 col-md-4 col-sm-4 col-4">
                                        <h6><a href="https://tourisme.biarritz.fr/es">Biarritz</a></h6>
                                    </div>
                                </div>
                           </div>


                           
                          

                        </div>
            
                </div>
                        
                       

                        
                        
                </div>

                <div class="row">
                    <div class="col-xl-12 text-center col-lg-12 col-md-12 col-sm-12 col-12">
                        <hr class="letra">
                    </div>
                </div>
    </div>

    <div class="row">
            <div class="col-xl-12 text-center col-lg-12 col-md-12 col-sm-12 col-12">
                <div id="copyright" style="margin-bottom: 1em;">     
                <a href="#container_cabecera">  Adrián Laya García © 2022  - superlaya50@gmail.com- </a>
                </div> 
            </div>
    </div> 

    </div>
</div>
</div>

<style>
    hr{margin: 0em;}
    h2{margin-top: 0.5em; margin-bottom: 0em; color:#006293;}
    h4{margin: 1em;}
    h5{font-size: 1em;margin-bottom: 0.7em;}
    h6{font-size: 0.7em; text-decoration: none;}
    .comunidades_destinos{margin: 0.5em;}
</style>