
<div class="row" style="border: 1px solid black; width: 90%; margin: auto; padding-bottom:1em;">

<div class="row" style="margin: 0 auto;">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <h6 class="modal-title">Valoraciones</h6>
    </div>
</div>



<div class="row" style="margin: 0 auto;">
    <div class="col-xl-12 text-center col-lg-12 col-md-12 col-sm-12 col-12">


<div class="col-xl-12 text-center col-lg-12 col-md-12 col-sm-12 col-12">

<!-- Carita 5-->
    <div class="row" data-reftag="" data-reviews-state-param="{&quot;filterByStar&quot;:&quot;five_star&quot;, &quot;pageNumber&quot;:&quot;1&quot;}" aria-label="El 65% de las reseñas tienen 5 estrellas" class="a-histogram-row a-align-center">

            <div class="aok-nowrap col-xl-12 text-center col-lg-12 col-md-12 col-sm-12 col-1">
            
                <span class="a-size-base">
                <!--
                    <a aria-disabled="true" class="a-link-normal 5star" title="El 65% de las reseñas tienen 5 estrellas" 
                    href="#"> 5 estrellas</a>-->
    
                    <i id="excelente-5" style="padding-top: 0.1em;" class="fa-regular fa-face-grin-hearts fa-1x"></i>   
                    
                </span>
    
                <span class="a-letter-space"></span>
                
            </div>
    
    
            <div class="a-span10 col-xl-12 text-center col-lg-12 col-md-12 col-sm-12 col-8">
                    <a aria-disabled="true" class="a-link-normal" title="El 65% de las reseñas tienen 5 estrellas" href="#">
                        <div id="barra_excelente" class="a-meter" role="progressbar" aria-valuenow="65%"></div>
                    </a>
            </div>
    
            <div class="a-text-right a-nowrap col-xl-12 col-lg-12 col-md-12 col-sm-12 col-2">  
                    <span class="a-letter-space"></span>
                    <span class="a-size-base"> <!--
                    <a aria-disabled="true" class="a-link-normal 5star" title="El 65% de las reseñas tienen 5 estrellas" 
                    href="#"> 5 estrellas</a>-->
                        <a id="textoporcentaje5" aria-disabled="true" class="a-link-normal" title="El 65% de las reseñas tienen 5 estrellas" href="#"></a>
                    </span>
            </div>
    </div>

 

<!-- Carita 4-->
    <div class="row" data-reftag="" data-reviews-state-param="{&quot;filterByStar&quot;:&quot;five_star&quot;, &quot;pageNumber&quot;:&quot;1&quot;}" aria-label="El 65% de las reseñas tienen 5 estrellas" class="a-histogram-row a-align-center">

            <div class="aok-nowrap col-xl-12 text-center col-lg-12 col-md-12 col-sm-12 col-1">
                
                <span class="a-size-base">
                <!--
                    <a aria-disabled="true" class="a-link-normal 5star" title="El 65% de las reseñas tienen 5 estrellas" 
                    href="#"> 5 estrellas</a>-->
    
                    <i id="muybueno-4" style="padding-top: 0.1em;" class="fa-regular fa-face-grin-wide fa-1x"></i>  
                    
                </span>
    
                <span class="a-letter-space"></span>
                
            </div>
    
    
            <div class="a-span10 col-xl-12 text-center col-lg-12 col-md-12 col-sm-12 col-8">
                    <a aria-disabled="true" class="a-link-normal" title="El 65% de las reseñas tienen 5 estrellas" href="#">
                        <div id="barra_muybueno" class="a-meter" role="progressbar" aria-valuenow="65%"></div>
                    </a>
            </div>
    
            <div class="a-text-right a-nowrap col-xl-12 col-lg-12 col-md-12 col-sm-12 col-2">  
                    <span class="a-letter-space"></span>
                    <span class="a-size-base"> <!--
                    <a aria-disabled="true" class="a-link-normal 5star" title="El 65% de las reseñas tienen 5 estrellas" 
                    href="#"> 5 estrellas</a>-->
                        <a id="textoporcentaje4" aria-disabled="true" class="a-link-normal" title="El 65% de las reseñas tienen 5 estrellas" href="#"></a>
                    </span>
            </div>
    </div>


<!--Carita 3-->
    <div class="row" data-reftag="" data-reviews-state-param="{&quot;filterByStar&quot;:&quot;five_star&quot;, &quot;pageNumber&quot;:&quot;1&quot;}" aria-label="El 65% de las reseñas tienen 5 estrellas" class="a-histogram-row a-align-center">

            <div class="aok-nowrap col-xl-12 text-center col-lg-12 col-md-12 col-sm-12 col-1">
            
                <span class="a-size-base">
                <!--
                    <a aria-disabled="true" class="a-link-normal 5star" title="El 65% de las reseñas tienen 5 estrellas" 
                    href="#"> 5 estrellas</a>-->
    
                    <i id="normal-3" style="padding-top: 0.1em;" class="fa-regular fa-face-meh fa-1x"></i>  
                    
                </span>
    
                <span class="a-letter-space"></span>
                
            </div>
    
    
            <div class="a-span10 col-xl-12 text-center col-lg-12 col-md-12 col-sm-12 col-8">
                    <a aria-disabled="true" class="a-link-normal" title="El 65% de las reseñas tienen 5 estrellas" href="#">
                        <div id="barra_normal" class="a-meter" role="progressbar" aria-valuenow="65%"></div>
                    </a>
            </div>
    
            <div class="a-text-right a-nowrap col-xl-12 col-lg-12 col-md-12 col-sm-12 col-2">  
                    <span class="a-letter-space"></span>
                    <span class="a-size-base"> <!--
                    <a aria-disabled="true" class="a-link-normal 5star" title="El 65% de las reseñas tienen 5 estrellas" 
                    href="#"> 5 estrellas</a>-->
                        <a id="textoporcentaje3" aria-disabled="true" class="a-link-normal" title="El 65% de las reseñas tienen 5 estrellas" href="#"></a>
                    </span>
            </div>
    </div>


<!-- Carita 2-->
    <div class="row" data-reftag="" data-reviews-state-param="{&quot;filterByStar&quot;:&quot;five_star&quot;, &quot;pageNumber&quot;:&quot;1&quot;}" aria-label="El 65% de las reseñas tienen 5 estrellas" class="a-histogram-row a-align-center">

            <div class="aok-nowrap col-xl-12 text-center col-lg-12 col-md-12 col-sm-12 col-1">
                
                <span class="a-size-base">
                <!--
                    <a aria-disabled="true" class="a-link-normal 5star" title="El 65% de las reseñas tienen 5 estrellas" 
                    href="#"> 5 estrellas</a>-->
    
                    <i id="malo-2" style="padding-top: 0.1em;" class="fa-regular fa-face-frown fa-1x"></i>  
                    
                </span>
    
                <span class="a-letter-space"></span>
                
            </div>
    
    
            <div class="a-span10 col-xl-12 text-center col-lg-12 col-md-12 col-sm-12 col-8">
                    <a aria-disabled="true" class="a-link-normal" title="El 65% de las reseñas tienen 5 estrellas" href="#">
                        <div id="barra_malo" class="a-meter" role="progressbar" aria-valuenow="65%"></div>
                    </a>
            </div>
    
            <div class="a-text-right a-nowrap col-xl-12 col-lg-12 col-md-12 col-sm-12 col-2">  
                    <span class="a-letter-space"></span>
                    <span class="a-size-base"> <!--
                    <a aria-disabled="true" class="a-link-normal 5star" title="El 65% de las reseñas tienen 5 estrellas" 
                    href="#"> 5 estrellas</a>-->
                        <a id="textoporcentaje2" aria-disabled="true" class="a-link-normal" title="El 65% de las reseñas tienen 5 estrellas" href="#"></a>
                    </span>
            </div>
    </div>




<!-- Carita 1-->
    <div class="row" data-reftag="" data-reviews-state-param="{&quot;filterByStar&quot;:&quot;five_star&quot;, &quot;pageNumber&quot;:&quot;1&quot;}" aria-label="El 65% de las reseñas tienen 5 estrellas" class="a-histogram-row a-align-center">

            <div class="aok-nowrap col-xl-12 text-center col-lg-12 col-md-12 col-sm-12 col-1">
                
            <span class="a-size-base">
                <!--
                    <a aria-disabled="true" class="a-link-normal 5star" title="El 65% de las reseñas tienen 5 estrellas" 
                    href="#"> 5 estrellas</a>-->
    
                    <i id="pesimo-1" style="padding-top: 0.1em;" class="fa-regular fa-face-angry fa-1x"></i>  
                    
                </span>
    
                <span class="a-letter-space"></span>
                
            </div>
    
    
            <div class="a-span10 col-xl-12 text-center col-lg-12 col-md-12 col-sm-12 col-8">
                    <a aria-disabled="true" class="a-link-normal" title="El 65% de las reseñas tienen 5 estrellas" href="#">
                        <div id="barra_pesimo" class="a-meter" role="progressbar" aria-valuenow="65%"></div>
                    </a>
            </div>
    
            <div class="a-text-right a-nowrap col-xl-12 col-lg-12 col-md-12 col-sm-12 col-2">  
                    <span class="a-letter-space"></span>
                    <span class="a-size-base"> <!--
                    <a aria-disabled="true" class="a-link-normal 5star" title="El 65% de las reseñas tienen 5 estrellas" 
                    href="#"> 5 estrellas</a>-->
                        <a id="textoporcentaje1" aria-disabled="true" class="a-link-normal" title="El 65% de las reseñas tienen 5 estrellas" href="#"></a>
                    </span>
            </div>
    </div>

</div>
    </div>

</div>

</div>


      
<style>

 .a-link-normal {
    color: #007185;
    font-size: 0.8em;
}
.a-span10{
padding-top: 0.8em;}

.a-nowrap{padding-left: 0em;}

.fa-regular{
    color: #007185;
}


h5{
color: #006293; text-decoration: underline 1px;
    /*border-bottom: 1px solid #006293;*/
    /*text-align: left; margin-top: 1em; padding-bottom: 0.1em;*/}


    .modal-body {
   
    padding: 0rem;
}




</style>




























    <style>
        .a-size-base {
    font-size: 1.5rem!important;
    line-height: 1.35!important;
  
}

.info_negocio a{font-size: 0.7em;}


.a-meter, .a-meter-with-txt {
    border-radius: 0.3rem;
}
    .a-meter, .a-meter-with-txt {
    overflow: hidden;
    box-shadow: inset 0 0 0 1px #e3e6e6;
    background-color: #F0F2F2;
    height: 0.5rem;
    margin-left: 1em;
}

.a-meter .a-meter-bar, .a-meter-with-txt .a-meter-bar {
    border-radius: 0.4rem;
    box-shadow: inset -2px 0 0 -1px #f5961d, inset 0 0 0 1px #de7921;
    background-color: #FFA41C;
    border-top-right-radius: 0;
    border-bottom-right-radius: 0;
}

.a-meter .a-meter-bar, .a-meter-with-txt .a-meter-bar {
    -webkit-transition: width .5s ease;
    transition: width 8.5s ease;
    float: left;
    font-size: 0;
    height: 100%;
    width: 0;
}

.a-nowrap {
    padding-left: 0em;
    text-align: left;
    margin-top: -0.3em;}
</style>
