<!--Tarjetitas a la derecha-->

<?php 

if($vecesvacio==0){?>
<style>
    .negociovacio{
        margin-top: 1em;
    }
</style>

<?php
$vecesvacio=1;

}


?>

    <div class="row negociovacio3" style="margin-left: 0em;">
        <div class='col-xl-12 text-center col-lg-12 col-md-12 col-sm-12 col-12'>
            <h6 class="espaciovacio">
                1/3 Reservado para su anuncio
            </h6>
        </div>
    </div>
<style>
  

.negociovacio3{
    background-color: #F8F9FA;
    border-radius:  0.3em 0.3em 0.3em 0.3em;
    border: 1px solid #c1c1c1; height: 90px; margin-top: 1em;
    padding: 0.45em; padding-bottom: 1.8em;
    /* box-shadow: 5px 5px 5px #888888; */
    box-shadow: inset 0px 0px 20px 4px #c1c1c1;
    
}

.negociovacio:hover{
     box-shadow: 1px 1px 10px 1px #888888; 
     border-radius:  0.6em;
}

.espaciovacio{
    text-align:center; margin-bottom: 2em;
}


/*
.tarjeta_foto img{
vertical-align: middle;
width: 150px;
}

p{
font-size: 0.8em; text-align: left;
}

*/
@media (max-width: 576px){
.negocio {
  

}
}

</style>       
