<li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-users"></i> Propietarios</a>

        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="index.php?ctl=nuevopropietarionegocio"><i class="fas fa-utensils"></i> Nuevo Propietario</a>
            <div class="dropdown-divider"></div>
          <!--  <a class="dropdown-item" href="index.php?ctl=borrarcliente"><i class="fas fa-trash-alt"></i> Borrar Cliente</a>-->
            <a class="dropdown-item" href="index.php?ctl=mostrartodosclientes"><i class="fas fa-eye"></i> Todos los Propietarios</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="index.php?ctl=borrartodosclientes"><i class="fas fa-trash-alt"></i> Borrar un Propietario</a>
          <!--  <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Otros</a>-->
        </div>
</li>