 <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle margin1" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" 
        aria-expanded="false">Bares y Restaurantes </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <!--<a class="dropdown-item" href="index.php?ctl=nuevaAgenciaViajes">Nueva Agencia de Viajes </a>  
            <a class="dropdown-item" class="nav-link " href="index.php?ctl=mostrartodasagenciabuses">Todas Agencias de Buses</a> 
            <a class="dropdown-item" href="index.php?ctl=nuevaagenciabuses">Nueva Agencia de buses</a>-->
            <a class="dropdown-item" href="index.php?ctl=cargarbarrestaurantes"><i class="fas fa-umbrella-beach"></i> Cargar Bares y Restaurantes</a>
            <a class="dropdown-item"  href="index.php?ctl=mostrartodosbaresrestaurantes">Todos Bares y Restaurantes</a> 
        </div>
  </li>