 
 <!-- Item para navegación Principal respecto a Agencias por parte del Administrador-->
  <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" 
        aria-expanded="false"><i class="fas fa-store-alt"></i> Agencias </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="index.php?ctl=nuevaAgenciaViajes"><i class="fas fa-store"></i> Nueva Agencia de Viajes </a> 
             <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="index.php?ctl=nuevaagenciabuses"><i class="fas fa-store"></i> Nueva Agencia de buses</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item"  href="index.php?ctl=mostraragenciaviajes"><i class="fas fa-eye"></i> Todas Agencias de Viajes</a>
            <div class="dropdown-divider"></div> 
            <a class="dropdown-item" class="nav-link " href="index.php?ctl=mostrartodasagenciabuses"><i class="fas fa-eye"></i> Todas Agencias de Buses</a> 
           
        </div>
  </li>