  <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-bus-alt"></i> Destinos</a>
        
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="nav-link" style="margin-top: 0em; padding-left: 0.5em; border: none;" href="index.php?ctl=mostrartodosdestinos"><i class="fas fa-umbrella-beach"></i> Listado 2023</a>
            <a class="nav-link" style="margin-top: 0em; padding-left: 0.5em;" href="index.php?ctl=cuadrobuscadoresdestinos"><i class="fas fa-umbrella-beach"></i> Buscador Destinos</a>
            <a class="nav-link" style="margin-top: 0em; padding-left: 0.5em; " href="index.php?ctl=mostraroficinasturismo"><i class="fas fa-utensils"></i> Oficinas Turismo</a>
          </div>
  
      </li>  