<?php
/*
use miId\fuente\Repositorio\DestinoRepositorio;
    $infoDestino=[];
    if (isset($_POST['cancelardestino'])){ $datos=$_POST['datos']; 

            if(isset($_POST['asegura'])){ 
                $obj=(new DestinoRepositorio())->borrarUnDestino($datos);

                if ($obj==true) {
                    ?><script>window.location.href="index.php?ctl=mostrartodosdestinosdeagenciaviajeslogeada";</script><?php
                } else {
                    ?><script>alert("No se ha podido eliminar el destino seleccionado!");</script><?php
                }
            } else{ ?>          
                <pre><script>alert("No ha seleccionado si está seguro de agregar este nuevo destino.!")</script></pre><?php
            }
    }*/
?>